//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FARABI.DB_context
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public int nid { get; set; }
        public string NTitle { get; set; }
        public string NDesc { get; set; }
        public string NDate { get; set; }
        public string status { get; set; }
        public string img { get; set; }
    }
}
